---
# tasks file for zato
- name: Install prerequisites
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - libffi-dev
    - python-software-properties

- name: Add Zato package signing key
  apt_key:
    url: https://zato.io/repo/zato-0CBD7F72.pgp.asc

- name: Add repositories
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - deb http://ftp.is.debian.org/debian wheezy-backports main
    - deb https://zato.io/repo/stable/2.0/debian wheezy main

- name: Install Zato
  apt:
    name: zato

- name: Create Zato cluster directory
  file:
    path: /opt/zato/zatocluster
    state: directory
  sudo_user: zato

- name: Create quickstart Zato cluster
  command: zato quickstart create /opt/zato/zatocluster sqlite localhost 6379 --kvdb_password ''
  args:
    creates: /opt/zato/zatocluster/zato-qs-start.sh
  sudo_user: zato
  register: quickstart 

- shell: "find /opt/zato/zatocluster/ -name pidfile | wc | awk '{print $1}'"
  register: pids

- name: Start Zato cluster
  command: "ssh {{ ansible_ssh_user }}@{{ ansible_ssh_host }} sudo -u zato -H -i /opt/zato/zatocluster/zato-qs-start.sh"
  connection: local
  sudo: false
  when: pids.stdout == "0"

- name: Cluster admin credentials
  debug:
    msg: "{{ ['These are your credentials for Zato Web Admin interface'] + quickstart.stdout_lines[-3].split(', ') }}"
  when: quickstart.changed
